stages:
  - test

variables:
  DEBUG: "1"

.pytest:
  stage: test
  tags:
    - qubes
  artifacts:
    when: always
    paths:
      - results
  before_script:
    - sudo dnf install -y python3-pathspec sequoia-sqv
  after_script:
    - mkdir $CI_PROJECT_DIR/results
    - cp -r ~/pytest-of-user/pytest-current/github-current/*.log $CI_PROJECT_DIR/results || true
    - cp -r ~/pytest-of-user/pytest-current/github-current/builder-github-logs $CI_PROJECT_DIR/results/


test_action:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --color=yes tests/test_action.py

test_command:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --color=yes tests/test_command.py

test_rpc:
  extends: .pytest
  script:
    - TMPDIR=~ pytest-3 -vvv --color=yes tests/test_rpc.py
