#!/bin/sh

# Combine ~/status/*status*.html files into ~/public_html/status.html

# shellcheck disable=SC2012
releases=$(ls ~/status/builder*status.html|
    sed -e 's/.*builder-\([^-]*\).*/\1/'|
    sort|
    uniq)

# html
(
cat ~/status/status-head.html
for rel in $releases; do
    printf '<h1>Release %s</h1>' "$rel"
    cat ~/status/builder-"$rel"*status.html
done
cat ~/status/status-foot.html
) > ~/public_html/status.html

# yaml
(
for rel in $releases; do
    printf '%s:\n' "$rel"
    # we increment yaml level to one
    cat ~/status/builder-"$rel"*status.yml | sed 's/^\(.*\)/  \1/g'
done
) > ~/public_html/status.yml